services:
  frontend:
    build: .
    env_file:
      - .env
    ports:
      - "7000:80"
    volumes:
      - app-data:/app
      - ./nginx/logs:/var/log/nginx
    restart: unless-stopped

volumes:
  app-data:
