services:
  frontend:
    build: .
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./entrypoint.sh:/entrypoint.sh
    restart: unless-stopped